recipe: default.v1

assistant_id: default_spacy_bot
language: "en" 


pipeline:
  - name: nlp_services.model_tokenizer.CustumWhitespaceTokenizer  # Still needed to break down text into tokens
    api_url: "http://localhost:8002/tokenize"
  - name: CountVectorsFeaturizer
    return_sequence: true
  - name: nlp_services.labse_embedder.LaBSEEmbedder  # Produces sentence-level embeddings
    api_url: "http://localhost:8002/encode"
  - name: DIETClassifier
    epochs: 100
    dense_dimension:
      text: 768  # Matches LaBSE output
      label: 768
    concat_dimension:
      text: 768  # Ensure this matches LaBSE and other feature sizes
      label: 768
    constrain_similarities: true
    mask_sequence: true  # Disable sequence masking to avoid mismatches
    pooling: average  # or 'max'
  - name: ResponseSelector
    epochs: 100

policies: null
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
